package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class UserTest {
    private AccountTokenPojo adminToken;
    private RestClient restClient;

    @BeforeClass
    private void auth() {
        restClient = new RestClient();
        adminToken = restClient.authenticate("admin", "setup");
    }

    @Test(description = "Pass len OK")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Create customer")
    public void createCustomerPassOkTest() {
        CustomerPojo customerPojo = restClient.createAutoGeneratedCustomer(adminToken);
        Assert.assertTrue(customerPojo.pass.length() >= 6);
        Assert.assertTrue(customerPojo.pass.length() <= 12);
    }

    @Test(description = "Login is valid")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Create customer")
    public void createCustomerValidLogin() {
        CustomerPojo customerPojo = restClient.createAutoGeneratedCustomer(adminToken);
        Assert.assertTrue(customerPojo.login.matches("^((?!\\.)[\\w-_.]*[^.])(@\\w+)(\\.\\w+(\\.\\w+)?[^.\\W])$"));
    }


}
